import type { Collaboration, Reel, User, UserType } from '@reelbazaar/config';

const now = new Date().toISOString();

export const demoUsers: Record<UserType | 'friend' | 'brandAlt', User> = {
  influencer: {
    id: 'demo-influencer',
    email: 'demo@reelbazaar.com',
    name: 'Didigam',
    userType: 'influencer',
    phone: '+91 98765 43210',
    gender: 'Male',
    dob: '1998-01-01',
    brandName: null,
    productCategories: ['Men', 'Women'],
    avatarUrl: null,
    firebaseUid: 'demo-influencer-uid',
    createdAt: now,
    updatedAt: now,
  },
  viewer: {
    id: 'demo-viewer',
    email: 'viewer@reelbazaar.com',
    name: 'Aarav Singh',
    userType: 'viewer',
    phone: null,
    gender: null,
    dob: '2000-01-01',
    brandName: null,
    productCategories: ['Men'],
    avatarUrl: null,
    firebaseUid: 'demo-viewer-uid',
    createdAt: now,
    updatedAt: now,
  },
  brand: {
    id: 'demo-brand',
    email: 'brand@reelbazaar.com',
    name: 'Maya Kapoor',
    userType: 'brand',
    phone: '+91 99887 77665',
    gender: null,
    dob: null,
    brandName: 'Aurora Atelier',
    productCategories: ['Women', 'Kids'],
    avatarUrl: null,
    firebaseUid: 'demo-brand-uid',
    createdAt: now,
    updatedAt: now,
  },
  friend: {
    id: 'demo-friend',
    email: 'friend@reelbazaar.com',
    name: 'Benjamin Moores',
    userType: 'brand',
    phone: null,
    gender: null,
    dob: null,
    brandName: 'Blue Orbit',
    productCategories: ['Men'],
    avatarUrl: null,
    firebaseUid: 'demo-friend-uid',
    createdAt: now,
    updatedAt: now,
  },
  brandAlt: {
    id: 'demo-brand-alt',
    email: 'claire@reelbazaar.com',
    name: 'Claire Dangais',
    userType: 'influencer',
    phone: null,
    gender: 'Female',
    dob: '2001-01-01',
    brandName: null,
    productCategories: ['Women'],
    avatarUrl: null,
    firebaseUid: 'demo-brand-alt-uid',
    createdAt: now,
    updatedAt: now,
  },
};

export function getDemoUser(userType: UserType): User {
  return demoUsers[userType];
}

export const demoReels: Reel[] = [
  {
    id: 'demo-reel-1',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: null,
    caption: 'Soft tailoring, pearl accents, and sunset-ready layers.',
    productLink: 'https://rb-app.nhancio.com',
    category: 'Women',
    creatorId: demoUsers.brandAlt.id,
    creator: demoUsers.brandAlt,
    brandTag: '@AuroraAtelier',
    likesCount: 122,
    viewsCount: 930,
    savesCount: 41,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-reel-2',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: null,
    caption: 'Streetwear capsule with electric blue details and layered denim.',
    productLink: 'https://rb-app.nhancio.com',
    category: 'Men',
    creatorId: demoUsers.influencer.id,
    creator: demoUsers.influencer,
    brandTag: '@BlueOrbit',
    likesCount: 88,
    viewsCount: 640,
    savesCount: 27,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-reel-3',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: null,
    caption: 'Mini edit for matching sets and weekend travel looks.',
    productLink: 'https://rb-app.nhancio.com',
    category: 'Kids',
    creatorId: demoUsers.brand.id,
    creator: demoUsers.brand,
    brandTag: '@TinyMuse',
    likesCount: 56,
    viewsCount: 402,
    savesCount: 18,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoCollaborations: Collaboration[] = [
  {
    id: 'demo-collab-1',
    brandId: demoUsers.brand.id,
    influencerId: demoUsers.influencer.id,
    brand: demoUsers.brand,
    influencer: demoUsers.influencer,
    score: 96,
    status: 'suggested',
    createdAt: now,
  },
  {
    id: 'demo-collab-2',
    brandId: demoUsers.friend.id,
    influencerId: demoUsers.influencer.id,
    brand: demoUsers.friend,
    influencer: demoUsers.influencer,
    score: 91,
    status: 'accepted',
    createdAt: now,
  },
];

