[build]
  base = "apps/landing-page"
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/app"
  to = "https://app.rava.one/"
  status = 301
  force = true

[[redirects]]
  from = "/app/*"
  to = "https://app.rava.one/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
